#*****************************************************************************************************************
- name: Rule 4.2.1.1 | Ensure rsyslog is installed
  yum:
      name: rsyslog
      state: present
  when:
      - rhel7cis_rule_4_2_1_1|bool
  tags:
      - level1
      - rsyslog
      - rule_4.2.1.1
#*****************************************************************************************************************
- name: Rule 4.2.1.2 | Ensure rsyslog Service is enabled and running
  systemd:
    name: rsyslog
    state: started
    enabled: yes
  when: 
     - rhel7cis_rule_4_2_1_2|bool
  tags:
      - level1
      - rsyslog
      - rule_4.2.1.2
#*****************************************************************************************************************
- name: Rule 4.2.1.3 | Ensure rsyslog default file permissions configured
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^\\$FileCreateMode'
    line: '$FileCreateMode 0640'
  when:
     - rhel7cis_rule_4_2_1_3|bool
  tags:
      - level1
      - rsyslog
      - rule_4.2.1.3
#*****************************************************************************************************************
- name: Rule 4.2.2.1 | Ensure journald is configured to send logs to rsyslog
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^ForwardToSyslog'
    line: 'ForwardToSyslog=yes'
  when:
     - rhel7cis_rule_4_2_2_1|bool
  tags:
      - level1
      - rsyslog
      - rule_4.2.2.1
#*****************************************************************************************************************
- name: Rule 4.2.2.2 | Ensure journald is configured to compress large log files
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^Compress'
    line: 'Compress=yes'
  when:
     - rhel7cis_rule_4_2_2_2|bool
  tags:
      - level1
      - rsyslog
      - rule_4.2.2.2
#*****************************************************************************************************************
- name: Rule 4.2.2.3 | Ensure journald is configured to write logfiles to persistent disk
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^Storage'
    line: 'Storage=persistent'
  when:
     - rhel7cis_rule_4_2_2_3|bool
  tags:
      - level1
      - rsyslog
      - rule_4.2.2.3




  


